export const invoicesList = [
  {
    name: "Albert mustang",
    email: "albertmustang@gmail.com",
    profilePicture: "https://bit.ly/ryan-florence",
    amount: "$100",
    status: "paid",
    date: "Aug 12, 2019",
  },
  {
    name: "Nandroid",
    email: "albertmustang@gmail.com",
    profilePicture: "https://bit.ly/kent-c-dodds",
    amount: "$500",
    status: "billing",
    date: "Aug 13, 2019",
  },
  {
    name: "Carls",
    email: "albertmustang@gmail.com",
    profilePicture: "https://bit.ly/code-beast",
    amount: "$970",
    status: "unpaid",
    date: "Aug 14, 2019",
  },
  {
    name: "Albert mustang",
    email: "albertmustang@gmail.com",
    profilePicture: "https://bit.ly/sage-adebayo",
    amount: "$100",
    status: "paid",
    date: "Aug 12, 2019",
  },
  {
    name: "Nandroid",
    email: "albertmustang@gmail.com",
    profilePicture: "https://bit.ly/ryan-florence",
    amount: "$500",
    status: "billing",
    date: "Aug 13, 2019",
  },
];
